### ISSUE TITLE
Error adding entities for domain sensor with platform repsolluzygas

### ISSUE THREAD

**Issue by silversegarra** [bzzoiro/repsolluzygas#16]
Hello to everyone, the integration is not working and entities are not present
Installed manually and trought HACS
Username and Password are correct
Home Assistant 2022.2.6
I dont have any invoice... maybe is that?
Any idea?

Thanks

**_Logger: homeassistant.components.sensor
Source: custom_components/repsolluzygas/sensor.py:61
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 14:44:44 (2 occurrences)
Last logged: 14:44:44

Error adding entities for domain sensor with platform repsolluzygas
Error while setting up repsolluzygas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 782, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/repsolluzygas/sensor.py", line 61, in state
    data = self.client.data.get(self.variable, 0)
AttributeError: 'RepsolLuzYGasSensor' object has no attribute 'data'_**

**Comment by LeidenSpain** [comment]
Hi, same problem

**Comment by silversegarra** [comment]
In my case, if the error is the bill, in a few days will be solved :)

**Comment by follares** [comment]
Mismo error por aquí.
Tampoco tengo la factura

**Comment by robertoclg** [comment]
Si el problema es que no existen facturas se puede solucionar editando el fichero repsol_api.py en la línea 183:
if len(invoices) > 0: #añadir esta línea
                data['last_invoice_amount'] = invoices[0]['amount']
                data['last_invoice_paid'] = invoices[0]['status'] == 'PAID'

**Comment by LeidenSpain** [comment]
Hi,

I have this lines on my version:
```
        if len(contracts) > 0:
            invoices = self.get_invoices(uid, signature, tstamp, contracts['house_id'], contract['contract_id'])
            data['last_invoice_amount'] = invoices[0]['amount']
            data['last_invoice_paid'] = invoices[0]['status'] == 'PAID'

```

Ah, change contracts for invoices

**Comment by LeidenSpain** [comment]
FUNCIONA
WORKS 

Ups. it turns out that I already have an invoice, so my test is worthless

**Comment by sagatxxx** [comment]
sigue sin funcionar aun cambiando lo que dice @robertoclg 
yo tampoco tengo la factura

me salen estos errores:


Logger: homeassistant.components.sensor
Source: custom_components/repsolluzygas/sensor.py:61
Integration: Sensor (documentation, issues)
First occurred: 11:19:27 (2 occurrences)
Last logged: 11:19:27

Error adding entities for domain sensor with platform repsolluzygas
Error while setting up repsolluzygas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 782, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/repsolluzygas/sensor.py", line 61, in state
    data = self.client.data.get(self.variable, 0)
AttributeError: 'RepsolLuzYGasSensor' object has no attribute 'data'

------

Logger: homeassistant.components.sensor
Source: custom_components/repsolluzygas/repsol_api.py:181
Integration: Sensor (documentation, issues)
First occurred: 11:19:25 (1 occurrences)
Last logged: 11:19:25

repsolluzygas: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/repsolluzygas/sensor.py", line 73, in update
    self.client.update()
  File "/config/custom_components/repsolluzygas/repsol_api.py", line 181, in update
    if len(invoices) > 0:
UnboundLocalError: local variable 'invoices' referenced before assignment

**Comment by sagatxxx** [comment]
ok funciona con el fork de @mmasipgu

**Comment by LeidenSpain** [comment]
> ok funciona con el fork de @mmasipgu

Ok, verifica no vaya a ser que ya tengas una factura, como me ha pasado a mi

**Comment by sagatxxx** [comment]
> Ok, verifica no vaya a ser que ya tengas una factura, como me ha pasado a mi

nop, no tengo todavía!
entré el último día :D

**Comment by mmasipgu** [comment]
Buenos días , en mi fork he quitado el sensor de última factura, por lo que los que somos nuevos clientes y no tenemos ninguna funciona sin problema.

**Comment by bzzoiro** [comment]
Buenos dias @mmasipgu y todos.

Si quieres, te doy acceso ADMIN  a este repo y te encargas de mantenerlo.
Yo no tengo mas Repsol asi que no puedo ayudarte

**Comment by mmasipgu** [comment]
Por mí no hay problema , todo lo que sea por colaborar ;)

**Comment by silversegarra** [comment]
> Por mí no hay problema , todo lo que sea por colaborar ;)

Buenas, puede ser que el fork, no muestre el gasto medio diario, ni el Repsol Total Days, cuando en la web, si que salen

**Comment by mmasipgu** [comment]
Aquí todos los valores en mi integración a día de hoy ![IMG_20220315_225249.jpg](https://user-images.githubusercontent.com/48867881/158478931-6ddf1cbf-a734-4f9f-a2ec-aa0850a86805.jpg)

**Comment by silversegarra** [comment]
Pero en tu caso ya tienes una factura?

**Comment by silversegarra** [comment]
![image](https://user-images.githubusercontent.com/29178492/158479410-44898742-5b1a-40da-bed4-e209d9b7c294.png)

**Comment by mmasipgu** [comment]
No, aún no , eso en mi fork es indiferente.

**Comment by silversegarra** [comment]
He puesto tu fork... voy a desinstalarlo y volverlo a poner, a ver si se me ha mezclado ;(

**Comment by silversegarra** [comment]
Bueno, algo pasa con mi cuenta, he probado la de mi madre y salen todos los datos... A ver si se soluciona ;(
Gracias por el curro

**Comment by pedropalamos** [comment]
Yo me estoy volviendo loco con la configuración, hace varias semanas me descargue la versión y la instalé manualmente en la carpeta <custom_components>, he añadido el texto de configuración dentro del Configuration.yaml con las contraseñas y usuario entre <>, pero no acabo de avanzar nada más, no hay nada dentro de la sección de componentes ni tampoco dentro de las integraciones. No se como continuar la configuración.
Alguna ayuda? Muchas gracias!
